# Generated by Django 3.1 on 2020-08-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
