# Generated by Django 3.1 on 2020-08-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_manager_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
