# Generated by Django 3.0.5 on 2020-10-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('access', models.CharField(max_length=100)),
                ('requrirements_field', models.BooleanField()),
                ('wireframes_field', models.BooleanField()),
                ('logo_field', models.BooleanField()),
                ('designing_field', models.BooleanField()),
                ('development_field', models.BooleanField()),
            ],
        ),
    ]
